#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
# This should be your name or nickname.
name: Emmett Hannigan

# Short bio or description aout you (displayed in the header)
description: Computer science junior who loves NLP. From NYC.

# CUSTOMIZE
# URL of your avatar or profile pic (you could use your GitHub profile pic)
#avatar: https://avatars1.githubusercontent.com/u/46607804?s=200&v=4
# fallback text in case image is not served and/or for screen readers
#avatar_alt_text: Avatar

# Flags below are optional - customize them if you wish
# The github flag should be replaced by your own github account name.
#
# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: emh550@nyu.edu
  facebook:
  flickr:
  github: emmetthannigan
  instagram:
  linkedin:
  pinterest:
  twitter:
  stackoverflow: 
  youtube: 
  googleplus: 


# Your website URL (e.g. https://nyu-ossd-s20.github.io/weekly )
# Replace the last part by the name of your own repository.
# It should be "/USER_NAME-weekly" in which USER_NAME is replaced by your actual
# user name for GitHub.

url: "https://nyu-ossd-s20.github.io/emmetthannigan-weekly"

# CUSTOMIZE
# Replace this with the name of your own repository.
# It should be "/USER_NAME-weekly" in which USER_NAME is replaced by your actual
# user name for GitHub.

baseurl: "/emmetthannigan-weekly"

#
# !! You don't need to change any of the configuration flags below !!
#   (but you may, if you know what you are doing)
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
